repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: requirements-txt-fixer
        files: ^requirements*.txt$
      - id: check-toml
      - id: pretty-format-json
        name: format-json
        args: [--autofix, --no-sort-keys]
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
      - id: mypy
        additional_dependencies: [ types-all ]
        exclude: ^tests/
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
  - repo: local
    hooks:
      - id: tox-check
        name: tox-check
        entry: tox -r -s -p all
        language: system
        pass_filenames: false
        always_run: true